### PR TITLE
rockchip_linux_defconfig: add wireguard driver

### PR DESCRIPTION
**Pull request by pymumu**
Signed-off-by: Nick Peng <pymumu@gmail.com>

### CODE REVIEW

**Comment by RadxaYuntian** [comment]
WireGuard is enabled in our [`bsp` build tool](https://github.com/radxa-repo/bsp/blob/main/linux/.common/kconfig.conf#L609-L610) which will enable the same features across multiple kernel branches.

**Comment by pymumu** [comment]
```
root@rock-5b:/mnt/lib/modules# find . | grep wireguard
root@rock-5b:/mnt/lib/modules# ls -lh
total 4.0K
drwxr-xr-x 3 root root 4.0K Dec  1 19:31 5.10.110-31-rockchip-ged1406c748b1
```
no wireguad driver found.
image version: rock-5b-debian-bullseye-xfce4-arm64-20221201-1424-gpt.img

**Comment by pymumu** [comment]
image

latest image，no wireguard driver

**Comment by RadxaStephen** [comment]
Try the image here. https://github.com/radxa-build/rock-5b/releases/tag/20230222-1109

Wireguard is added I think.

**Comment by Dark-Existed** [comment]
> Try the image here. https://github.com/radxa-build/rock-5b/releases/tag/20230222-1109
> 
> Wireguard is added I think.

Can this image boot on nvme? I used to try this image's old version on nvme but failed.

**Comment by RadxaYuntian** [comment]
We didn't test this image for NVMe boot. To be more specific this image is untested at all, as our focus is currently on other products. However, NVMe boot mostly depends on having the right bootloader installed in SPI. So if you already got that part done you can give this image a shot.

**Comment by pymumu** [comment]
Why not enable wireguard in the official version?  Is it difficult to enable wireguard？

**Comment by RadxaYuntian** [comment]
As I said earlier we currently do not have resource to create and test a new system release for ROCK 5B.

**Comment by pymumu** [comment]
rock pi users download image from here: https://github.com/radxa/debos-radxa/releases follow the guide: https://wiki.radxa.com/Rock5/downloads
but these images do not include wireguard driver.

you said: 
> wireGuard is enabled in our [`bsp` build tool](https://github.com/radxa-repo/bsp/blob/main/linux/.common/kconfig.conf#L609-L610) which will enable the same features across multiple kernel branches.

but in fact , the image released here: https://github.com/radxa/debos-radxa/releases is not include this driver.

about this PR, i just want to enable this module for these images: https://github.com/radxa/debos-radxa/releases

**Comment by RadxaYuntian** [comment]
[debos-radxa](https://github.com/radxa/debos-radxa) is deprecated. Plus, the images under its release pages are the same nature of the pre-release images from [radxa-build](https://github.com/radxa-build/rock-5b/) that they are both untested unless explicitly listed on our Wiki download page.

I think your problem is confusing the GitHub CI generated images as our official release. They are only deemed as official release after testing to make sure there is no breaking bugs, and right now there is no resource for that for 5B.

For users who are willing to risk running unstable software, it is available under [radxa-build](https://github.com/radxa-build/rock-5b/), which should have wireguard enabled.

**Pull request closed without merging**
