### PR TITLE
Add pwm-fan to rock-5b devicetree

### PR DESCRIPTION
**Pull request by SmartElec**
Register pwmfan to cooling device.
And user can use interface `/sys/class/thermal/cooling_device0/cur_state` to control

### CODE REVIEW

**Comment by RadxaYuntian** [comment]
其实没有必要把之前的PR关掉的

**Comment by ginkage** [comment]
I tried this change, but the automatic fan control (as defined by thermal zones) doesn't seem to work for me.
Writing 0-4 to `/sys/class/thermal/cooling_device0/cur_state` works fine though.

**Comment by RadxaYuntian** [comment]
I think you need to enable step wise governor as well.

**Comment by ginkage** [comment]
Tested, and can confirm: with step wise governor this PR enables fan controls without any extra software. Maybe turn it on by default in the config as well?

**Comment by RadxaYuntian** [comment]
The current default governor I believe is better for fan-less device. When we later rework ROCK 5B's image we will include tools for user to override default governor on boot.

As the development is now moved to `linux-5.10-gen-rkr3.4` I'll close this PR for now.

**Pull request closed without merging**
