### PR TITLE
Kubernetes support configs: nf_tables,BPF support sets

### PR DESCRIPTION
**Pull request by opsiff**
To support kubernetes 
Need to open some Netfilter supports
Fix issue : [rockchip-linux#273](https://github.com/rockchip-linux/kernel/issues/273)

It may causes about 600KB~1MB vmlinux image increase and makes it as 'M'(as ko not in vmlinux)。
change diffs: 
154,181d153
< CONFIG_NF_TABLES=m
< CONFIG_NF_TABLES_INET=y
< CONFIG_NF_TABLES_NETDEV=y
< CONFIG_NFT_NUMGEN=m
< CONFIG_NFT_CT=m
< CONFIG_NFT_FLOW_OFFLOAD=m
< CONFIG_NFT_COUNTER=m
< CONFIG_NFT_CONNLIMIT=m
< CONFIG_NFT_LOG=m
< CONFIG_NFT_LIMIT=m
< CONFIG_NFT_MASQ=m
< CONFIG_NFT_REDIR=m
< CONFIG_NFT_NAT=m
< CONFIG_NFT_TUNNEL=m
< CONFIG_NFT_OBJREF=m
< CONFIG_NFT_QUEUE=m
< CONFIG_NFT_QUOTA=m
< CONFIG_NFT_REJECT=m
< CONFIG_NFT_COMPAT=m
< CONFIG_NFT_HASH=m
< CONFIG_NFT_XFRM=m
< CONFIG_NFT_SOCKET=m
< CONFIG_NFT_OSF=m
< CONFIG_NFT_TPROXY=m
< CONFIG_NFT_DUP_NETDEV=m
< CONFIG_NFT_FWD_NETDEV=m
< CONFIG_NF_FLOW_TABLE_INET=m
< CONFIG_NF_FLOW_TABLE=m

and

< CONFIG_NETFILTER_XT_TARGET_CT=m
description: Xtables: connection tracking target

Signed-off-by: Wentao Guan <otgwt@outlook.com>

### CODE REVIEW

**Comment by CodeChenL** [comment]
@RadxaStephen Can you merge this PR🤔? I'll turn on bpf on top of this to support Docker😁.

**Comment by CodeChenL** [comment]
hello， @opsiff .When I turn on CONFIG_BPF_PRELOAD, there will be a compilation error, have you tried to compile?

**Comment by opsiff** [comment]
> hello， @opsiff .When I turn on CONFIG_BPF_PRELOAD, there will be a compilation error, have you tried to compile?

yeh,as for"No libelf found"(https://github.com/opsiff/linux-rockpi5-rk3588/actions/runs/3275116259/jobs/5389547414) ,it just like a depend packege error(libelf lost?).

**Comment by CodeChenL** [comment]
> 
maybe，When I turn off CONFIG_BPF_PRELOAD，there will be a compilation successfully，docker also works fine

**Comment by opsiff** [comment]
> > 
> 
> maybe，When I turn off CONFIG_BPF_PRELOAD，there will be a compilation successfully，docker also works fine

Thanks for you reply,as we do not need CONFIG_BPF_PRELOAD for this thread,i will remove that.

**Comment by opsiff** [comment]
> > > 
> > 
> > 
> > maybe，When I turn off CONFIG_BPF_PRELOAD，there will be a compilation successfully，docker also works fine
> 
> Thanks for you reply,as we do not need CONFIG_BPF_PRELOAD for this thread,i will remove that.

I believe that as we use cross-compile environment,if we open CONFIG_BPF_PRELOAD ,we need to cross-compile libelf and so on lib with cross-compile before we compile kernel finally or We download with arm deb repo...

**Comment by CodeChenL** [comment]
> > > > 
> > > 
> > > 
> > > maybe，When I turn off CONFIG_BPF_PRELOAD，there will be a compilation successfully，docker also works fine
> > 
> > 
> > Thanks for you reply,as we do not need CONFIG_BPF_PRELOAD for this thread,i will remove that.
> 
> I believe that as we use cross-compile environment,if we open CONFIG_BPF_PRELOAD ,we need to cross-compile libelf and so on lib with cross-compile before we compile kernel finally or We download with arm deb repo...

I compiled on rock5 and I've installed the libelf library via apt,but it still compiles error
```shell
rock@rock-5b:~$ sudo apt search libelf
[sudo] password for rock:
Sorting... Done
Full Text Search... Done
libdwarf++0/stable 0.3-2.1 arm64
  C++11 DWARF parser

libelf++0/stable 0.3-2.1 arm64
  C++11 ELF parser

libelf-dev/stable,now 0.183-1 arm64 [installed,automatic]
  libelf1 development libraries and header files

libelf1/stable,now 0.183-1 arm64 [installed,automatic]
  library to read and write ELF files

libelfin-dev/stable 0.3-2.1 arm64
  C++11 ELF/DWARF parser (development files)

rock@rock-5b:~$

```

**Comment by opsiff** [comment]
> > > > > 
> > > > 
> > > > 
> > > > maybe，When I turn off CONFIG_BPF_PRELOAD，there will be a compilation successfully，docker also works fine
> > > 
> > > 
> > > Thanks for you reply,as we do not need CONFIG_BPF_PRELOAD for this thread,i will remove that.
> > 
> > 
> > I believe that as we use cross-compile environment,if we open CONFIG_BPF_PRELOAD ,we need to cross-compile libelf and so on lib with cross-compile before we compile kernel finally or We download with arm deb repo...
> 
> I compiled on rock5 and I've installed the libelf library via apt,but it still compiles error
> 
> ```shell
> rock@rock-5b:~$ sudo apt search libelf
> [sudo] password for rock:
> Sorting... Done
> Full Text Search... Done
> libdwarf++0/stable 0.3-2.1 arm64
>   C++11 DWARF parser
> 
> libelf++0/stable 0.3-2.1 arm64
>   C++11 ELF parser
> 
> libelf-dev/stable,now 0.183-1 arm64 [installed,automatic]
>   libelf1 development libraries and header files
> 
> libelf1/stable,now 0.183-1 arm64 [installed,automatic]
>   library to read and write ELF files
> 
> libelfin-dev/stable 0.3-2.1 arm64
>   C++11 ELF/DWARF parser (development files)
> 
> rock@rock-5b:~$
> ```

Could you upload your compile log via pastebin like paste.debian.net ?

**Comment by CodeChenL** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > maybe，When I turn off CONFIG_BPF_PRELOAD，there will be a compilation successfully，docker also works fine
> > > > 
> > > > 
> > > > Thanks for you reply,as we do not need CONFIG_BPF_PRELOAD for this thread,i will remove that.
> > > 
> > > 
> > > I believe that as we use cross-compile environment,if we open CONFIG_BPF_PRELOAD ,we need to cross-compile libelf and so on lib with cross-compile before we compile kernel finally or We download with arm deb repo...
> > 
> > 
> > I compiled on rock5 and I've installed the libelf library via apt,but it still compiles error
> > ```shell
> > rock@rock-5b:~$ sudo apt search libelf
> > [sudo] password for rock:
> > Sorting... Done
> > Full Text Search... Done
> > libdwarf++0/stable 0.3-2.1 arm64
> >   C++11 DWARF parser
> > 
> > libelf++0/stable 0.3-2.1 arm64
> >   C++11 ELF parser
> > 
> > libelf-dev/stable,now 0.183-1 arm64 [installed,automatic]
> >   libelf1 development libraries and header files
> > 
> > libelf1/stable,now 0.183-1 arm64 [installed,automatic]
> >   library to read and write ELF files
> > 
> > libelfin-dev/stable 0.3-2.1 arm64
> >   C++11 ELF/DWARF parser (development files)
> > 
> > rock@rock-5b:~$
> > ```
> 
> Could you upload your compile log via pastebin like paste.debian.net ?

I'll recompile later, and I remember almost identical to your log

**Comment by opsiff** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > maybe，When I turn off CONFIG_BPF_PRELOAD，there will be a compilation successfully，docker also works fine
> > > > > 
> > > > > 
> > > > > Thanks for you reply,as we do not need CONFIG_BPF_PRELOAD for this thread,i will remove that.
> > > > 
> > > > 
> > > > I believe that as we use cross-compile environment,if we open CONFIG_BPF_PRELOAD ,we need to cross-compile libelf and so on lib with cross-compile before we compile kernel finally or We download with arm deb repo...
> > > 
> > > 
> > > I compiled on rock5 and I've installed the libelf library via apt,but it still compiles error
> > > ```shell
> > > rock@rock-5b:~$ sudo apt search libelf
> > > [sudo] password for rock:
> > > Sorting... Done
> > > Full Text Search... Done
> > > libdwarf++0/stable 0.3-2.1 arm64
> > >   C++11 DWARF parser
> > > 
> > > libelf++0/stable 0.3-2.1 arm64
> > >   C++11 ELF parser
> > > 
> > > libelf-dev/stable,now 0.183-1 arm64 [installed,automatic]
> > >   libelf1 development libraries and header files
> > > 
> > > libelf1/stable,now 0.183-1 arm64 [installed,automatic]
> > >   library to read and write ELF files
> > > 
> > > libelfin-dev/stable 0.3-2.1 arm64
> > >   C++11 ELF/DWARF parser (development files)
> > > 
> > > rock@rock-5b:~$
> > > ```
> > 
> > 
> > Could you upload your compile log via pastebin like paste.debian.net ?
> 
> I'll recompile later, and I remember almost identical to your log

Thanks,I will also try to compile in a faster high performance native arm64 computer later.

**Comment by opsiff** [comment]
> > > > > 
> > > > 
> > > > 
> > > > maybe，When I turn off CONFIG_BPF_PRELOAD，there will be a compilation successfully，docker also works fine
> > > 
> > > 
> > > Thanks for you reply,as we do not need CONFIG_BPF_PRELOAD for this thread,i will remove that.
> > 
> > 
> > I believe that as we use cross-compile environment,if we open CONFIG_BPF_PRELOAD ,we need to cross-compile libelf and so on lib with cross-compile before we compile kernel finally or We download with arm deb repo...
> 
> I compiled on rock5 and I've installed the libelf library via apt,but it still compiles error
> 
> ```shell
> rock@rock-5b:~$ sudo apt search libelf
> [sudo] password for rock:
> Sorting... Done
> Full Text Search... Done
> libdwarf++0/stable 0.3-2.1 arm64
>   C++11 DWARF parser
> 
> libelf++0/stable 0.3-2.1 arm64
>   C++11 ELF parser
> 
> libelf-dev/stable,now 0.183-1 arm64 [installed,automatic]
>   libelf1 development libraries and header files
> 
> libelf1/stable,now 0.183-1 arm64 [installed,automatic]
>   library to read and write ELF files
> 
> libelfin-dev/stable 0.3-2.1 arm64
>   C++11 ELF/DWARF parser (development files)
> 
> rock@rock-5b:~$
> ```

I guess that as action logs say ,we need libelf-dev libbpfcc-dev zlib1g-dev.

**Comment by CodeChenL** [comment]
> > > > > > > > 
> > > > > > > 
> > > > > > > 
> > > > > > > maybe，When I turn off CONFIG_BPF_PRELOAD，there will be a compilation successfully，docker also works fine
> > > > > > 
> > > > > > 
> > > > > > Thanks for you reply,as we do not need CONFIG_BPF_PRELOAD for this thread,i will remove that.
> > > > > 
> > > > > 
> > > > > I believe that as we use cross-compile environment,if we open CONFIG_BPF_PRELOAD ,we need to cross-compile libelf and so on lib with cross-compile before we compile kernel finally or We download with arm deb repo...
> > > > 
> > > > 
> > > > I compiled on rock5 and I've installed the libelf library via apt,but it still compiles error
> > > > ```shell
> > > > rock@rock-5b:~$ sudo apt search libelf
> > > > [sudo] password for rock:
> > > > Sorting... Done
> > > > Full Text Search... Done
> > > > libdwarf++0/stable 0.3-2.1 arm64
> > > >   C++11 DWARF parser
> > > > 
> > > > libelf++0/stable 0.3-2.1 arm64
> > > >   C++11 ELF parser
> > > > 
> > > > libelf-dev/stable,now 0.183-1 arm64 [installed,automatic]
> > > >   libelf1 development libraries and header files
> > > > 
> > > > libelf1/stable,now 0.183-1 arm64 [installed,automatic]
> > > >   library to read and write ELF files
> > > > 
> > > > libelfin-dev/stable 0.3-2.1 arm64
> > > >   C++11 ELF/DWARF parser (development files)
> > > > 
> > > > rock@rock-5b:~$
> > > > ```
> > > 
> > > 
> > > Could you upload your compile log via pastebin like paste.debian.net ?
> > 
> > 
> > I'll recompile later, and I remember almost identical to your log
> 
> Thanks,I will also try to compile in a faster high performance native arm64 computer later.

this is my compile log on rock 5b
```shell
rock@rock-5b:~/kernel$ make -j3
  SYNC    include/config/auto.conf.cmd
  UPD     include/config/kernel.release
  UPD     include/generated/utsrelease.h
  CALL    scripts/atomic/check-atomics.sh
  CALL    scripts/checksyscalls.sh
  CHK     include/generated/compile.h
  UPD     include/generated/compile.h
  CC      init/version.o
  CC      kernel/sys.o
  AR      init/built-in.a
  CC      kernel/module.o
  UPD     kernel/config_data
  CC      kernel/trace/trace.o
  AR      kernel/trace/built-in.a
  AR      kernel/bpf/preload/built-in.a
  CC [M]  kernel/bpf/preload/bpf_preload_kern.o
/bin/sh: 1: ./scripts/gcc-wrapper.py: not found
/bin/sh: 1: ./scripts/gcc-wrapper.py: not found

Auto-detecting system features:
...                        libelf: [ OFF ]
...                          zlib: [ OFF ]
...                           bpf: [ OFF ]

No libelf found
make[4]: *** [Makefile:287: elfdep] Error 1
make[3]: *** [kernel/bpf/preload/Makefile:11: kernel/bpf/preload/libbpf.a] Error 2
make[2]: *** [scripts/Makefile.build:516: kernel/bpf/preload] Error 2
make[1]: *** [scripts/Makefile.build:516: kernel/bpf] Error 2
make: *** [Makefile:1915: kernel] Error 2
make: *** Waiting for unfinished jobs....
  CC      drivers/base/firmware_loader/main.o
  AR      drivers/base/firmware_loader/built-in.a
  AR      drivers/base/built-in.a
  CC      drivers/input/touchscreen/gt1x/gt1x_tools.o
  AR      drivers/input/touchscreen/gt1x/built-in.a
  AR      drivers/input/touchscreen/built-in.a
  AR      drivers/input/built-in.a
  CC [M]  drivers/net/bonding/bond_main.o
  CC [M]  drivers/net/team/team.o
  CC [M]  drivers/net/bonding/bond_procfs.o
  LD [M]  drivers/net/bonding/bonding.o
  CC [M]  drivers/target/target_core_configfs.o
  CC [M]  drivers/vhost/scsi.o
  AR      drivers/built-in.a
  LD [M]  drivers/vhost/vhost_scsi.o
  LD [M]  drivers/target/target_core_mod.o
rock@rock-5b:~/kernel$
```

**Comment by CodeChenL** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > maybe，When I turn off CONFIG_BPF_PRELOAD，there will be a compilation successfully，docker also works fine
> > > > 
> > > > 
> > > > Thanks for you reply,as we do not need CONFIG_BPF_PRELOAD for this thread,i will remove that.
> > > 
> > > 
> > > I believe that as we use cross-compile environment,if we open CONFIG_BPF_PRELOAD ,we need to cross-compile libelf and so on lib with cross-compile before we compile kernel finally or We download with arm deb repo...
> > 
> > 
> > I compiled on rock5 and I've installed the libelf library via apt,but it still compiles error
> > ```shell
> > rock@rock-5b:~$ sudo apt search libelf
> > [sudo] password for rock:
> > Sorting... Done
> > Full Text Search... Done
> > libdwarf++0/stable 0.3-2.1 arm64
> >   C++11 DWARF parser
> > 
> > libelf++0/stable 0.3-2.1 arm64
> >   C++11 ELF parser
> > 
> > libelf-dev/stable,now 0.183-1 arm64 [installed,automatic]
> >   libelf1 development libraries and header files
> > 
> > libelf1/stable,now 0.183-1 arm64 [installed,automatic]
> >   library to read and write ELF files
> > 
> > libelfin-dev/stable 0.3-2.1 arm64
> >   C++11 ELF/DWARF parser (development files)
> > 
> > rock@rock-5b:~$
> > ```
> 
> I 猜 that as action logs say ,we need libelf-dev libbpfcc-dev zlib1g-dev.

i

> > > > > > 
> > > > > 
> > > > > 
> > > > > maybe，When I turn off CONFIG_BPF_PRELOAD，there will be a compilation successfully，docker also works fine
> > > > 
> > > > 
> > > > Thanks for you reply,as we do not need CONFIG_BPF_PRELOAD for this thread,i will remove that.
> > > 
> > > 
> > > I believe that as we use cross-compile environment,if we open CONFIG_BPF_PRELOAD ,we need to cross-compile libelf and so on lib with cross-compile before we compile kernel finally or We download with arm deb repo...
> > 
> > 
> > I compiled on rock5 and I've installed the libelf library via apt,but it still compiles error
> > ```shell
> > rock@rock-5b:~$ sudo apt search libelf
> > [sudo] password for rock:
> > Sorting... Done
> > Full Text Search... Done
> > libdwarf++0/stable 0.3-2.1 arm64
> >   C++11 DWARF parser
> > 
> > libelf++0/stable 0.3-2.1 arm64
> >   C++11 ELF parser
> > 
> > libelf-dev/stable,now 0.183-1 arm64 [installed,automatic]
> >   libelf1 development libraries and header files
> > 
> > libelf1/stable,now 0.183-1 arm64 [installed,automatic]
> >   library to read and write ELF files
> > 
> > libelfin-dev/stable 0.3-2.1 arm64
> >   C++11 ELF/DWARF parser (development files)
> > 
> > rock@rock-5b:~$
> > ```
> 
> I guess that as action logs say ,we need libelf-dev libbpfcc-dev zlib1g-dev.

i try it,but is same

**Comment by opsiff** [comment]
> > 
> > I guess that as action logs say ,we need libelf-dev libbpfcc-dev zlib1g-dev.
> 
> i try it,but is same

..... very strange ,but i may find a way to make successfully.

Use Clang instead of GCC .
with native arm64 platform use (make CC=clang) instead of (make) ,on libelf time ,it says ok.

update:use clang ,it build successfully.
clang version 12.0.1
more info:
https://paste.debian.net/1257684/

**Comment by CodeChenL** [comment]
> 

when is use clang,it is compilation successfully too!
my  gcc and clang version:
```shell
rock@rock-5b:~$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/10/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 10.2.1-6' --with-bugurl=file:///usr/share/doc/gcc-10/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-10 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-mutex
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.1 20210110 (Debian 10.2.1-6)
rock@rock-5b:~$ clang -v
Debian clang version 11.0.1-2
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/aarch64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/aarch64-linux-gnu/10
Selected GCC installation: /usr/bin/../lib/gcc/aarch64-linux-gnu/10
Candidate multilib: .;@m64
Selected multilib: .;@m64
rock@rock-5b:~$

```

**Pull request merged**
