### PR TITLE
rockchip_linux_defconfig: enable BLK_DEV_NBD=m

### LINKED ISSUE #303: Unable to install kubernetes csi-rbdplugin (rook-ceph) due to module nbd not found
embedded board: Radxa Rock 5b
system image: [rock-5b-ubuntu-focal-server-arm64-20230201-1200-gpt.img.xz](https://github.com/radxa/debos-radxa/releases/download/20230201-0944/rock-5b-ubuntu-focal-server-arm64-20230201-1200-gpt.img.xz)
ubuntu server version: 20.04.6

step docs: https://kubesphere.cloud/docs/ksv/02-quick-start/01-install-ksv-in-single-node-mode/

```shell
rock@rock-5b:~$ sudo su
./install.sh -a --ratio 3
# ...
kubectl get pod -A
```

```shell
NAMESPACE           NAME                                                READY   STATUS             RESTARTS   AGE
kube-system         coredns-7448499f4d-85mp6                            1/1     Running            0          70m
kube-system         kube-multus-ds-prtmn                                1/1     Running            0          70m
kube-system         kube-ovn-cni-qqf2c                                  1/1     Running            0          70m
kube-system         kube-ovn-controller-94c9596c4-brd44                 1/1     Running            0          70m
kube-system         kube-ovn-monitor-7c98d98457-pzsfg                   1/1     Running            0          70m
kube-system         kube-ovn-pinger-ksjb4                               1/1     Running            0          69m
kube-system         ovn-central-668ff5988f-j8fhx                        1/1     Running            0          70m
kube-system         ovs-ovn-cmr4c                                       1/1     Running            0          70m
kubekey-system      kubekey-controller-manager-9b55dbfd5-j9d6b          2/2     Running            0          70m
kubesphere-system   ks-installer-5cbb65bdf5-c45jj                       1/1     Running            0          70m
kubesphere-system   minio-7f687756bb-fvh5t                              0/1     Pending            0          65m
rook-ceph           csi-rbdplugin-254f7                                 2/3     CrashLoopBackOff   17         66m
rook-ceph           csi-rbdplugin-provisioner-7dfb48857f-88bqm          6/6     Running            0          66m
rook-ceph           rook-ceph-crashcollector-rock-5b-66c67c6946-hdp2g   1/1     Running            0          64m
rook-ceph           rook-ceph-mgr-a-744d5bbb45-hm96k                    1/1     Running            0          64m
rook-ceph           rook-ceph-mon-a-f548555b4-6kfhh                     1/1     Running            0          65m
rook-ceph           rook-ceph-operator-5fdc669785-9nszp                 1/1     Running            0          67m
rook-ceph           rook-ceph-osd-0-7c76d846d5-x9v7m                    0/1     CrashLoopBackOff   16         62m
rook-ceph           rook-ceph-osd-prepare-rock-5b-7xcms                 0/1     Completed          0          59m
rook-ceph           rook-ceph-tools-6c55fbd449-4j496                    1/1     Running            0          67m
rook-ceph           rook-discover-vhqbz                                 1/1     Running            0          66m
rook-ceph           snapshot-controller-0                               1/1     Running            0          67m
```

```shell
kubectl logs -n rook-ceph csi-rbdplugin-254f7 csi-rbdplugin
```

```shell
W0706 08:05:02.918278   40415 rbd_attach.go:209] rbd-nbd: nbd modprobe failed with error an error (exit status 1) occurred while running modprobe args: [nbd]
E0706 08:05:03.002118   40415 rbd_util.go:241] modprobe failed: an error (exit status 1) occurred while running modprobe args: [rbd]
F0706 08:05:03.002490   40415 driver.go:148] an error (exit status 1) occurred while running modprobe args: [rbd]
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0x1)
        /go/src/github.com/ceph/ceph-csi/vendor/k8s.io/klog/v2/klog.go:1038 +0xac
# ...
```

```shell
modprobe nbd
```

```shell
modprobe: FATAL: Module nbd not found in directory /lib/modules/5.10.110-37-rockchip-g74457be0716d
```

### PR DESCRIPTION
**Pull request by jikunchong**
close [rockchip-linux/kernel#303](https://github.com/rockchip-linux/kernel/issues/303)

kubectl logs -n rook-ceph csi-rbdplugin-254f7 csi-rbdplugin

W0706 08:05:02.918278   40415 rbd_attach.go:209] rbd-nbd: nbd modprobe failed with error an error (exit status 1) occurred while running modprobe args: [nbd]
E0706 08:05:03.002118   40415 rbd_util.go:241] modprobe failed: an error (exit status 1) occurred while running modprobe args: [rbd]
F0706 08:05:03.002490   40415 driver.go:148] an error (exit status 1) occurred while running modprobe args: [rbd]
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0x1)
        /go/src/github.com/ceph/ceph-csi/vendor/k8s.io/klog/v2/klog.go:1038 +0xac
# ...

### CODE REVIEW

**Comment by RadxaYuntian** [comment]
It is [enabled](https://github.com/radxa-repo/bsp/blob/main/linux/.common/kconfig.conf#L752) when building with our `bsp` tool.

**Comment by RadxaStephen** [comment]
I will add this to rockchip_linux_defconfig.

**Comment by RadxaStephen** [comment]
@jikunchong 

Hi, thanks for your work.

I have two suggestions.
The first one is for a full git commit message, a signed-by-off is needed. Would you mine adding the Signed-off-by?
The second one is about the title. Add the file that you want to change. That would make the meaning of the title clearer.
For an example, "rockchip_linux_defconfig: enable BLK_DEV_NBD".

**Comment by jikunchong** [comment]
I have successfully built the kernel and installed rook-ceph on Kubernetes. Looking forward to providing an official image that supports the NBD module in the future.

**Pull request closed without merging**
