### PR TITLE
configs: built-in CONFIG_FB

### PR DESCRIPTION
**Pull request by Ken-Vamrs**

### CODE REVIEW

**Review by RadxaYuntian — CHANGES_REQUESTED** [review]
built-in

**Comment by RadxaYuntian** [comment]
https://applink.feishu.cn/client/message/link/open?token=AmY%2FRdMxxQABZnveo%2BQRAAM%3D

**Comment by RadxaYuntian** [comment]
不是build是built啊

**Review by RadxaYuntian — APPROVED** [review]

**Comment by RadxaStephen** [comment]
Added to branch linux-6.1-stan-rkr1. https://github.com/radxa/kernel/commit/64ff16134ce5ce21fceb96bee1c460cdc9bb96e4

**Pull request closed without merging**
