### PR TITLE
hwmon: (emc2305) add support for EMC2301/2/3/5 RPM-based PWM Fan Spee…

### PR DESCRIPTION
**Pull request by nascs**
…d Controller.

Add driver for Microchip EMC2301/2/3/5 RPM-based PWM Fan Speed Controller.
Modify Makefile and Kconfig to support Microchip EMC2305 RPM-based
PWM Fan Speed Controller.

Signed-off-by: Michael Shych <michaelsh@nvidia.com>
Reviewed-by: Vadim Pasternak <vadimp@nvidia.com>
Signed-off-by: Nascs Fang <nascs@radxa.com>

### CODE REVIEW

**Comment by RadxaYuntian** [comment]
需要确认能不能配置风扇后进行控制。raspi有几个相关的[提交](https://github.com/raspberrypi/linux/commits/rpi-6.1.y/drivers/hwmon/emc2305.c).

**Comment by RadxaYuntian** [comment]
1. [6fbbcd7](https://github.com/radxa/kernel/pull/191/commits/6fbbcd7971885eee59275b20caf2a5d47cd01e80) 不是cherrypicked,原作者信息丢失
2. rpi树里面紧跟着还有个修复补丁

**Comment by RadxaYuntian** [comment]
先自测一下，没问题的话这里回复一下

**Comment by nascs** [comment]
> 先自测一下，没问题的话这里回复一下

测试结果和昨天是一样的

radxa@radxa-cm3-rpi-cm4-io:~$ cat /sys/class/thermal/cooling_device1/type 
emc2305_fan

这个 type 默认的是 emc2305_fan， 不是 emc2305_fan1/emc2305_fan2/emc2305_fan3/emc2305_fan4/emc2305_fan5

**Pull request merged**
