### PR TITLE
Enable pwm-fan and set default thermal policy to STEP_WISE

### PR DESCRIPTION
**Pull request by hbiyik**
This is necessary for rock5b pwm fan to operate

### CODE REVIEW

**Comment by RadxaYuntian** [comment]
This kernel and config file is shared with multiple products which may not include a fan, and even in case of 5B
 the fan is an optional add-on. This is why the default thermal governor is power_allocator which operates passively.

pwm-fan is [enabled globally](https://github.com/radxa-repo/bsp/blob/main/linux/.common/kconfig.conf#L565) in our `bsp` build script to ensure a consistent feature set across different kernel versions. It doesn't hurt to enable it here as well.

**Comment by hbiyik** [comment]
ok this means that i am building Archlinux kernels wrong. I was only using $BSP_DEFCONFIG, which is rockchip_linux_defconfig. But after analyzing your comment, i noticed that .common/kconfig.conf is merged with scripts/Kconfig/merge_config.sh merged on top of rockchip_linux_defconfig.

This should mean that .deb package of latest kernel which is rkr3.4 based should also have this enabled, is my understanding correct?

**Comment by RadxaYuntian** [comment]
This is correct and we have working PWM fan support in 5A and 5B for a while.

**Comment by hbiyik** [comment]
ok then closing this PR, thanks for clearifactions..

**Pull request closed without merging**
