### PR TITLE
add pwm fan support for rock-5b

### PR DESCRIPTION
**Pull request by amazingfate**
works from #42 , merging to new branch

### CODE REVIEW

**Comment by RadxaYuntian** [comment]
On 4C+ I added [fan](https://github.com/radxa-repo/bsp/blob/main/linux/rockchip/0020-rock4/0006-Add-pwm-fan-for-ROCK-4C.patch) to soc_thermal zone. Not quite sure the difference between those 2 approaches.

**Comment by RadxaYuntian** [comment]
I guess the difference is you have temperature directly tied to fan speed, while in my approach it is managed by `step_wise` governor`.

**Comment by amazingfate** [comment]
I think there is no difference between these thermal zones. `step_wise` always works. I also tried this patch on rock-3a, pwm-fan added to soc_thermal.

**Comment by amazingfate** [comment]
My patch is based on the [mainline kernel Document](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/devicetree/bindings/hwmon/pwm-fan.txt?h=v6.2-rc7).

**Pull request closed without merging**
