### PR TITLE
Sync panthor with armbian

### PR DESCRIPTION
**Pull request by CodeChenL**
* https://github.com/armbian/linux-rockchip/pull/260
* https://github.com/armbian/linux-rockchip/pull/264

### CODE REVIEW

**Comment by RadxaYuntian** [comment]
https://github.com/armbian/linux-rockchip/pull/210

**Comment by CodeChenL** [comment]
> [armbian/linux-rockchip#210](https://github.com/armbian/linux-rockchip/pull/210)

已经合过了https://github.com/radxa/kernel/commits/linux-6.1-stan-rkr4.1/drivers/gpu/drm/panthor

**Comment by RadxaYuntian** [comment]
那我们的代码顺序跟armbian是反着了：https://github.com/armbian/linux-rockchip/commits/rk-6.1-rkr3/?after=7d54e5474cf840533fcc862d3f3bd978e00fb2d5+1

**Review by RadxaYuntian — APPROVED** [review]

**Comment by CodeChenL** [comment]
> 那我们的代码顺序跟armbian是反着了：https://github.com/armbian/linux-rockchip/commits/rk-6.1-rkr3/?after=7d54e5474cf840533fcc862d3f3bd978e00fb2d5+1

https://github.com/radxa/kernel/commits/linux-6.1-stan-rkr1/drivers/gpu/drm/panthor rkr1的时候是正的，是不是@RadxaStephen迁移到rkr4.1的时候搞反了？

**Comment by RadxaStephen** [comment]
Merged.

**Pull request closed without merging**
