### PR TITLE
arm64: dts: rockchip: rename panthor and mali gpu node for rk3588

### PR DESCRIPTION
**Pull request by CodeChenL**
Fix panthor driver not working properly

### CODE REVIEW

**Review by MakiseKurisu — APPROVED** [review]

**Review by RadxaYuntian — APPROVED** [review]

**Comment by nyanmisaka** [comment]
FYI the Panthor and Mali blob (Bifrost) are incompatible with each other. Therefore the OpenCL runtime will not be available if Panthor is enabled. It's better to release both images, or use an overlay to make Panthor opt-in.

**Comment by CodeChenL** [comment]
@StephenInVamrs 先别合并，发现检测是否正常驱动方法有问题

**Comment by RadxaYuntian** [comment]
> Therefore the OpenCL runtime will not be available if Panthor is enabled.

Here is a tutorial to extrace OpenCL runtime that we are willing to try: https://clehaxze.tw/gemlog/2023/06-17-setting-up-opencl-on-rk3588-using-libmali.gmi



> It's better to release both images, or use an overlay to make Panthor opt-in.

We will provide an overlay to enable Mali. Panthor (as well as panfrost) will be the default GPU driver for the simple fact that we are getting way too many support questions about their OpenGL applications run badly, as well as bad desktop performance.

**Comment by CodeChenL** [comment]
> @StephenInVamrs 先别合并，发现检测是否正常驱动方法有问题

@StephenInVamrs 没问题可以合并了

**Comment by RadxaStephen** [comment]
I changes the git title a little bit. Added it.

**Pull request closed without merging**
