### PR TITLE
arm64: dts: rk356x: use consistent name for HDMI sound

### PR DESCRIPTION
**Pull request by RadxaNaoki**
tested on cm3-io and rock 3a

### CODE REVIEW

**Review by RadxaYuntian — COMMENTED** [review]
I believe `rockchip-hdmiX` was used with `rockchip,hdmi` sound driver, and the property is `rockchip,card-name`. I'm not too familiar with the upstream sound driver. Did you observe any difference between and after the change?

**Comment by RadxaNaoki** [comment]
it's just a cosmetic change.

before
```
radxa@radxa-cm3-io:~$ cat /proc/asound/cards
 0 [rockchiphdmi   ]: rockchip_hdmi - rockchip,hdmi
                      rockchip,hdmi
```
after
```
radxa@radxa-cm3-io:~$ cat /proc/asound/cards
 0 [rockchiphdmi0  ]: rockchip-hdmi0 - rockchip-hdmi0
                      rockchip-hdmi0
```

`rockchip,hdmi` is used in rockchip 5.10 kernel, but not used in rockchip 4.19 kernel

**Review by RadxaYuntian — APPROVED** [review]
I'll approve this change. But just so you know, we are tying to upgrade RK356X platforms to [linux-5.10-gen-rkr4.1](https://github.com/radxa/kernel/tree/linux-5.10-gen-rkr4.1) branch, so @RadxaStephen may not merge this after all.

**Comment by RadxaStephen** [comment]
I also accept this commit.

**Pull request merged**
