### PR TITLE
arm64: dts: rk3588: swap cursor and display plane

### PR DESCRIPTION
**Pull request by RadxaYuntian**
This property is causing mouse cursor becoming hidden on ROCK 5A & 5B.

Disable it for CM3 just in case.

Fixes Redmine 3021, Rockchip 408946.

### CODE REVIEW

**Comment by RadxaYuntian** [comment]
Waiting for He Rui's confirmation.

**Comment by RadxaStephen** [comment]
@RadxaYuntian    One pr related to cursor. https://github.com/radxa/kernel/pull/50

**Comment by RadxaYuntian** [comment]
Cursor issue was reported in [this thread](https://forum.radxa.com/t/flickering-cursor/13398/23).

**Comment by RadxaYuntian** [comment]
With this change the cursor seems to be stable.

**Comment by RadxaStephen** [comment]
Great.

**Comment by amazingfate** [comment]
primary plane is changed to `ROCKCHIP_VOP2_CLUSTER0`, but cluster plane doesn't support gstreamer's kmssink. What's the root cause of cursor disappear?

**Comment by RadxaYuntian** [comment]
After comparing with previous good version we found the issue was introduced in #50. Rockchip suggested to us to use esmart for cursor-win-id for this specific issue.

**Comment by amazingfate** [comment]
With the current devicetree I can use this pipeline to use kmssink:
```
gst-launch-1.0 -e videotestsrc ! video/x-raw,format=NV12,width=1920,height=1080,framerate=60/1 ! kmssink plane-id=71
```

**Pull request merged**
